services:
  nextjs-app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules # Simple anonymous volume
