services:
  nextjs-app:
    build:
      context: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app

#      - node_modules_folder:/app/node_modules # named volume for node_modules
#volumes:
#  node_modules_folder: #declaration of named volume
